import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { C, serif, sans } from '../theme';

const EFFECTIVE_DATE = 'July 5, 2026';

const h2 = { fontFamily: serif, fontSize: 22, color: C.text, marginBottom: 12, marginTop: 40 };
const p  = { fontSize: 15, color: '#4a4038', lineHeight: 1.85, marginBottom: 16, fontFamily: sans };
const ul = { fontSize: 15, color: '#4a4038', lineHeight: 1.85, paddingLeft: 24, marginBottom: 16, fontFamily: sans };

export default function Terms() {
  return (
    <div style={{ background: C.bg }}>
      <Navbar />

      <div style={{ maxWidth: 760, margin: '0 auto', padding: '80px 24px 60px' }}>

        {/* Header */}
        <div style={{ marginBottom: 48 }}>
          <p style={{ fontSize: 12, fontWeight: 800, letterSpacing: 1, color: C.roseDark, textTransform: 'uppercase', marginBottom: 12, fontFamily: sans }}>Legal</p>
          <h1 style={{ fontFamily: serif, fontSize: 'clamp(32px, 5vw, 48px)', color: C.text, letterSpacing: -0.5, marginBottom: 16 }}>Terms of Service</h1>
          <p style={{ fontSize: 14, color: C.muted, fontFamily: sans }}>Effective date: {EFFECTIVE_DATE}</p>
        </div>

        <p style={p}>
          Please read these Terms of Service ("Terms") carefully before using Aiden. By creating an account or using our iOS app or website, you agree to be bound by these Terms. If you do not agree to these Terms, please do not use Aiden.
        </p>

        <h2 style={h2}>1. About Aiden</h2>
        <p style={p}>
          Aiden is a caregiving organisation and coordination platform designed to help family caregivers manage care recipients' health information, appointments, medications, insurance details, and related logistics. Aiden is operated by Aiden Caregiving, LLC ("we," "our," or "us").
        </p>
        <p style={p}>
          Aiden is a personal productivity and information management tool. It is <strong>not</strong> a medical provider, health plan, financial advisor, or legal services firm. Nothing in Aiden — including content generated by the Ask Aiden AI assistant — constitutes medical, legal, or financial advice.
        </p>

        <h2 style={h2}>2. Eligibility</h2>
        <p style={p}>
          You must be at least 18 years old to create an account and use Aiden. By using the service, you represent that you are 18 or older and have the legal capacity to enter into these Terms.
        </p>
        <p style={p}>
          Aiden is intended for personal, non-commercial use by individual caregivers. Use of Aiden by healthcare organisations, institutions, or agencies in a professional capacity requires our prior written consent.
        </p>

        <h2 style={h2}>3. Your Account</h2>
        <p style={p}>
          You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account. Please use a strong, unique password and do not share your credentials with others.
        </p>
        <p style={p}>
          If you become aware of any unauthorised access to your account, please notify us immediately at <a href="mailto:support@aiden.care" style={{ color: C.roseDark }}>support@aiden.care</a>.
        </p>
        <p style={p}>
          You may not create accounts for others without their explicit consent or create multiple accounts for the purpose of circumventing restrictions.
        </p>

        <h2 style={h2}>4. Information You Enter</h2>
        <p style={p}>
          You retain ownership of all information you enter into Aiden, including care recipient profiles, health data, notes, and documents. By entering this information, you grant us a limited licence to store, process, and display it solely for the purpose of providing the Aiden service to you.
        </p>
        <p style={p}>
          You represent that you have the right to enter the information you provide — including information about your care recipients — and that doing so does not violate any applicable laws or third-party rights.
        </p>
        <p style={p}>
          You are solely responsible for the accuracy and completeness of the information you enter. Aiden does not verify health records, insurance details, or any other data you provide.
        </p>

        <h2 style={h2}>5. Permitted and Prohibited Uses</h2>
        <p style={p}>You may use Aiden only for lawful caregiving coordination and personal organisation purposes. You agree not to:</p>
        <ul style={ul}>
          <li>Use Aiden to store or share information you do not have the right to access or disclose</li>
          <li>Attempt to access other users' accounts or data</li>
          <li>Reverse-engineer, decompile, or disassemble any part of the Aiden platform</li>
          <li>Use automated tools, bots, or scrapers to access or extract data from Aiden</li>
          <li>Use Aiden in any way that could damage, overburden, or impair our systems</li>
          <li>Introduce viruses, malware, or other harmful code</li>
          <li>Resell, sublicence, or otherwise commercialise the service without our written consent</li>
          <li>Use Aiden to violate any applicable law or regulation</li>
        </ul>

        <h2 style={h2}>6. The Ask Aiden AI Assistant</h2>
        <p style={p}>
          Aiden includes an AI-powered assistant ("Ask Aiden") that can answer questions about caregiving, medical conditions, insurance, legal documents, and related topics. Ask Aiden is designed to provide general information to support caregiving decisions — it is not a substitute for professional medical, legal, or financial advice.
        </p>
        <p style={p}>
          AI-generated responses may be inaccurate, incomplete, or out of date. Always verify important information with qualified professionals, and never delay seeking emergency medical care based on a response from Ask Aiden.
        </p>
        <p style={p}>
          We reserve the right to monitor, modify, or discontinue the Ask Aiden feature at any time.
        </p>

        <h2 style={h2}>7. Subscription and Payments</h2>
        <p style={p}>
          Aiden offers a free tier as well as optional paid subscription plans. Paid plans are billed on a monthly or annual basis as selected at the time of purchase. All fees are stated in US dollars and are non-refundable except where required by applicable law.
        </p>
        <p style={p}>
          You may cancel your subscription at any time from your account settings. Cancellation takes effect at the end of the current billing period — you will retain access to paid features until that date.
        </p>
        <p style={p}>
          We reserve the right to change our pricing with at least 30 days' notice. Continued use of a paid plan after the effective date of a price change constitutes acceptance of the new pricing.
        </p>

        <h2 style={h2}>8. Intellectual Property</h2>
        <p style={p}>
          Aiden and all of its content — including the logo, user interface design, written content, and software — are owned by us and protected by copyright, trademark, and other intellectual property laws. You may not copy, modify, distribute, or create derivative works from our platform or content without our prior written consent.
        </p>
        <p style={p}>
          The "Aiden" name and logo are trademarks of Aiden Caregiving, LLC. You may not use our trademarks without our explicit written permission.
        </p>

        <h2 style={h2}>9. Third-Party Services</h2>
        <p style={p}>
          Aiden integrates with or links to third-party services, including Firebase (Google Cloud), reminder delivery providers, and external resources. These services are governed by their own terms and privacy policies. We are not responsible for the practices or content of any third-party services.
        </p>

        <h2 style={h2}>10. Disclaimers</h2>
        <p style={p}>
          Aiden is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not warrant that the service will be uninterrupted, error-free, or free of harmful components.
        </p>
        <p style={p}>
          We do not make any warranties regarding the accuracy or completeness of any content on the platform, including AI-generated content, insurance summaries, or caregiving guidance. All such content is for informational purposes only.
        </p>

        <h2 style={h2}>11. Limitation of Liability</h2>
        <p style={p}>
          To the fullest extent permitted by applicable law, Aiden Caregiving, LLC and its officers, directors, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages — including loss of data, loss of revenue, or harm resulting from reliance on information provided through the service — even if we have been advised of the possibility of such damages.
        </p>
        <p style={p}>
          Our total liability for any claim arising from your use of Aiden shall not exceed the greater of (a) the amount you paid to us in the 12 months preceding the claim, or (b) $50.
        </p>

        <h2 style={h2}>12. Indemnification</h2>
        <p style={p}>
          You agree to indemnify and hold harmless Aiden and its affiliates from any claims, damages, losses, or expenses (including legal fees) arising from your use of the service, your violation of these Terms, or your violation of any third-party rights.
        </p>

        <h2 style={h2}>13. Termination</h2>
        <p style={p}>
          You may stop using Aiden and delete your account at any time. We may suspend or terminate your access to Aiden at our discretion if we believe you have violated these Terms, engaged in fraudulent activity, or if required by law.
        </p>
        <p style={p}>
          Upon termination, your right to use the service ceases immediately. Sections of these Terms that by their nature should survive termination — including intellectual property, disclaimers, and limitation of liability — will continue to apply.
        </p>

        <h2 style={h2}>14. Changes to These Terms</h2>
        <p style={p}>
          We may update these Terms from time to time. When we make material changes, we will notify you via email or in-app notice at least 14 days before the changes take effect. Your continued use of Aiden after the effective date constitutes your acceptance of the revised Terms.
        </p>

        <h2 style={h2}>15. Governing Law and Disputes</h2>
        <p style={p}>
          These Terms are governed by the laws of the State of California, without regard to conflict of law principles. Any disputes arising under these Terms shall be resolved through binding arbitration under the rules of the American Arbitration Association, conducted in San Francisco, California, except that either party may seek injunctive relief in a court of competent jurisdiction.
        </p>
        <p style={p}>
          You waive any right to participate in a class-action lawsuit or class-wide arbitration related to your use of Aiden.
        </p>

        <h2 style={h2}>16. Contact Us</h2>
        <p style={p}>If you have questions about these Terms, please contact us:</p>
        <p style={{ ...p, background: C.bgWarm, borderRadius: 14, padding: '20px 24px', border: `1px solid ${C.border}` }}>
          <strong>Aiden Caregiving, LLC</strong><br />
          Email: <a href="mailto:legal@aiden.care" style={{ color: C.roseDark }}>legal@aiden.care</a><br />
          Website: aiden.care
        </p>

      </div>

      <Footer />
    </div>
  );
}
